config/routes.rb
Rails.application.routes.draw do
  get "home/top" => "home#top"
  post "login" => "sessions#create"
  post "logout" => "sessions#destroy"

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :user_id, { presence: true }
    validates :post_id, { presence: true }
    validates :content, { presence: true }
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :post
    belongs_to :user

    validates :user_id, { presence: true }
    validates :post_id, { presence: true }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :delete_all

  has_many :comments, dependent: :delete_all
  #default_scope -> { order(created_at: :desc) }

  mount_uploader :picture, PictureUploader
  validates :picture, { presence: true }
  validates :content, { presence: true, length: { maximum: 250 } }
  validates :user_id, { presence: true }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :delete_all
  has_many :likes, dependent: :delete_all
  has_many :comments, dependent: :delete_all

  mount_uploader :image, ImageUploader
  validates :nickname, { presence: true, uniqueness: true }
  validates :email, { presence: true, uniqueness: true }
  validates :password, { presence: true } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_current_user

  private
  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if @current_user.blank?
      redirect_to new_login_path, notice: "ログインしてください"
    end  
  end  

  def forbid_login_user
    if @current_user.present?
      redirect_to posts_path, notice: "既にログインしています"
    end
  end    

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = @current_user.id
    @comment.post_id = params[:post_id]
    @comment.save
    @post = Post.find(params[:post_id])
    redirect_to post_path(@post), notice: "投稿が作成されました！"
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
		@user = User.new
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user
  before_action :set_post

  def create
    @like = Like.new(post_id: params[:post_id], user_id: @current_user.id)
    @like.save
  end

  def destroy
    like = Like.find_by(post_id: params[:post_id], user_id: @current_user.id) 
    like.destroy
  end

  private
  def like_params
    params.permit(:post_id, :user_id)
  end

  def set_post
    @post = Post.find_by(id: params[:post_id])
  end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user 
  before_action :ensure_corret_user_of_post, only: [:edit, :destroy]
  
  def index
    @posts = Post.includes(:user, :likes).all.order(created_at: :desc)
    @post = Post.new
  end

  def show
    @post = Post.includes(:likes).find_by(id: params[:id])
    @comments = @post.comments.includes(:user).all.order(created_at: :desc)
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = @current_user.id
    if @post.save
      redirect_to posts_path, notice: "投稿が作成されました！"
    else
      render :new
    end
  end
  
  def edit
    @post = Post.find_by(id: params[:id])
  end
  
  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
     redirect_to posts_path, notice: "投稿を編集しました"
    else 
     render :edit
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if @post.destroy
      redirect_to posts_path, notice: "投稿を削除しました"
    else
      redirect_to posts_path, alert: "削除に失敗しました"
    end 
  end

  private
  def post_params
    params.require(:post).permit(:content, :picture)
  end

  def ensure_corret_user_of_post
    @post = Post.find_by(id: params[:id]) 
    if @current_user != @post.user
      redirect_to posts_path, notice: "他のユーザーの投稿は編集・削除できません"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :forbid_login_user, only: [:new]
  
  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to posts_path, notice: "ログインしました"
    else
      @email = params[:email]
      flash[:alert] = "メールアドレスかパスワードが違います"
      render "/home/top"
    end  
  end 
 
  def destroy
    reset_session
    redirect_to "/home/top", notice: "ログアウトしました"
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:index, :show, :edit, :update]
  before_action :forbid_login_user, only: [:new, :create]
  before_action :ensure_corret_user, only: [:edit, :update]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts.includes(:likes).all.order(created_at: :desc)
    @post = Post.new
  end

  def create
    @user = User.new(user_params)  
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "アカウントを作成しました"
    else
      render :new  
    end
  end

  def edit
    @user = User.find_by(id: params[:id]) 
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました"
    else
      render :edit
    end
  end    
    
  private
  def ensure_corret_user
    if session[:user_id] != params[:id].to_i
      redirect_to posts_path, notice: "他のユーザーの情報は編集できません"
    end
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :image)
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="main-home-top">
  <div class="container">
    <div class="top-wrapper">
      <div class="top-logo">This is Tweeting</div>
      <div class="top-content">What do you want to say?</div>
    </div>  

    <!-- 新規登録modal -->
    <div id="signup-modal">
      <div class="modal-basic">
        <div class="close-modal"><i class="glyphicon glyphicon-remove"></i></div>
        <h1 class="form-heading">Do you want to join us??</h1>
        <div class="form-users-form">
          <%= render partial: "partials/error_message", locals: { thing: @user } %>
          <%= form_for (@user) do |f| %>
            <div class="form-group">
              <%= f.label :nickname, "Nickname" %>
              <%= f.text_field :nickname, :class => "form-control", :placeholder => "Nickname" %>
            </div>
            <div class="form-group">
              <%= f.label :email, "Email" %>
              <%= f.email_field :email, :class => "form-control", :placeholder => "Email" %>
            </div>
            <div class="form-group">
              <%= f.label :image, "Image" %>
              <%= f.file_field :image %>
            </div>
            <div class="form-group">  
              <%= f.label :password, "Password" %>
              <%= f.password_field :password, :class => "form-control", :placeholder => "Password" %>
            </div>
            <div class="form-group">
              <%= f.submit "新規作成", :class => "btn btn-success modal-btn" %>
            </div>
          <% end %>
        </div>
      </div>  
    </div>

    <!-- ログインmodal --> 
    <div id="login-modal">
      <div class="modal-basic">
        <div class="close-modal"><i class="glyphicon glyphicon-remove"></i></div>
        <h1 class="form-heading">Please Login!</h1>
        <div class="form users-form">
          <div class="form-body">
            <% if @error_message %>
              <div class="form-error">
                <%= @error_message %>
              </div>
            <% end %>
            <%= form_tag("/login") do %>
              <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email" value="<%= @email %>" id="email" placeholder="email" class="form-control">
              </div>
              <div class="form-group">  
                <label for ="password">Password</label>
                <input type="password" name="password" id="password" placeholder="password" class="form-control">
              </div>  
              <input type="submit" value="Login!" class="btn btn-primary modal-btn">
            <% end %>
          </div>
        </div>
      </div>  
    </div>

    <div class="main-wrapper">
      <div>

      </div>
    </div>
  </div>   
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweeting2</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".target">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand">Tweeting</a>
      </div>
      <div class="collapse navbar-collapse target"> 
        <ul class="nav navbar-nav">
          <% if @current_user %>
            <li><%= link_to @current_user.nickname, user_path(@current_user) %></li>
            <li><%= link_to("ホーム", posts_path) %></li>
            <li><%= link_to("友達リスト", users_path) %></li>            
          <% else %>
            <li><a id="signup-modal-show" class="pointer">新規作成</a></li> 
            <li><a id="login-modal-show" class="pointer">ログイン</a></li>           
          <% end %>          
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if @current_user %>
            <li><%= link_to("Logout　　", "/logout", method: :post ) %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    <div class=flash_notice>
      <% if flash[:notice] %>
        <%= flash[:notice] %>
      <% end %>  
    </div>
    <div class=flash_alert>  
      <% if flash[:alert] %>
        <%= flash[:alert] %>
      <% end %>  
    </div>
  <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<span class="like-botton">
	<% isfound = false %>
	<% post.likes.each do |like| %>
		<% if like.user_id == @current_user.id %>  
			<div>
				<%= link_to post_like_path(like, post_id: post.id), method: :delete, remote: true, id: "like-botton" do %>
					<i class="glyphicon glyphicon-heart color-red"></i>
					<%= post.likes.all.count %>
				<% end %>
			</div>
			<% isfound = true %>
			<% break %>
		<% end %>
	<% end %>    
	<% if (!isfound) %>
		<div>
			<%= link_to post_likes_path(post_id: post.id), method: :post,  remote: true, id: "like-botton" do %>
				<i class="glyphicon glyphicon-heart color-gray"></i>
				<%= post.likes.all.count %>
			<% end %>
		</div>
	<% end %>
</span>  

app/views/likes/create.js.erb
$("#like-of-<%= @post.id %>").html("<%= j(render partial: 'like', locals: { post: @post}) %>");

app/views/likes/destroy.js.erb
$("#like-of-<%= @post.id %>").html("<%= j(render partial: 'like', locals: { post: @post}) %>");

app/views/partials/_error_message.html.erb
<% thing.errors.full_messages.each do |message| %>
    <div class="form-error">
        <%= message %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<tr>   
  <td>
  <div class="post-wrapper">
    <%= link_to(user_path(post.user)) do %>
      <%= image_tag post.user.image.thumb.url, class: "post-user-image" %>
      <span class="post-user-name">
        <%= post.user.nickname %>
      </span> 
    <% end %> 
  <span class="post-created_at">
    <%= post.created_at %>
  </span>
    <br>
    <%= link_to(post_path(post)) do %>
      <br>
      <%= image_tag post.picture.thumb.url, class: "post-picture" %><br>
      <div class="post-content">
        <%= post.content %><br>
      </div>  
    <% end %>
    <span id="like-of-<%= post.id %>">
      <%= render :partial => "likes/like", locals: { post: post } %> 
    </span>
  </div>    
  </td>  
</tr>

app/views/posts/edit.html.erb
<div class="main posts-edit">
  <div class="container">
    <h1 class="form-heading">Do you want to edit this post?</h1>
    <%= form_for (@post) do |f| %>
        <div class="form-body">
          <%= render partial: "partials/error_message", locals: { thing: @post } %>
          <%= f.file_field :picture %>
          <%= f.text_area :content, :class => "form-control" %>
          <%= f.submit "編集", :class => "btn btn-success" %>  
        </div>
    <% end %> 
  </div>  
</div>

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
    <div class="menu-left">
    <%= link_to(user_path(@current_user)) do %>
      <h2><%= @current_user.nickname %></h2>
      <%= image_tag @current_user.image.thumb.url,class: "current-user-image" %>
    <% end %>    
      <h3 class="form-heading">今の気持ちを写真と一緒に投稿しよう！</h3>
      <%= form_for (@post) do |f| %>
        <div class="form">
          <div class="form-body">
            <%= render partial: "partials/error_message", locals: { thing: @post } %>
          </div>
          <div class="form-body">
            <%= f.file_field :picture, :class => "form-control"  %>
          </div>
          <div class="form-body">  
            <%= f.text_area :content, :class => "form-control" %>
          </div>
          <div class="form-body">
            <%= f.submit "投稿", :class => "btn btn-success" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="menu-right">
      <h1>What comes to your mind...</h1>
      <% if @posts.empty? %>
        <div class="no-posts">
          まだ投稿がありません
        </div>
      <% else %>
        <table class="table table-bordered">
          <%= render :partial => "posts/post", :collection => @posts %>
        </table>
      <% end %>   
    </div>  
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">今の気持ちを写真と一緒に投稿しよう！</h1>
    <%= form_for (@post) do |f| %>
      <div class="form">
        <div class="form-body">
           <%= render partial: "partials/error_message", locals: { thing: @post } %>
           <%= f.file_field :picture %>
           <%= f.text_area :content, :class => "form-control" %>
           <%= f.submit "投稿", :class => "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">
      <%= render :partial => "post", locals: { post: @post } %> 
      <% if @current_user == @post.user %>
        <%= link_to("Edit", edit_post_path(@post)) %>
        <%= link_to("delete", post_path(@post), method: :delete) %>
      <% end %>
      <%= link_to("Back to list", posts_path) %>
    </div>
    <table class="table table-bordered">
      <% @comments.each do |comment| %>   
        <tr>
          <td>
            <%= link_to(user_path(comment.user)) do %>
              <%= image_tag comment.user.image.thumb.url, class: "post-user-image" %>
              <span class="post-user-name">
                <%= comment.user.nickname %>
              </span>
            <% end %> 
            <span class="post-created_at">
              <%= comment.created_at %><br>
            </span>
            <div class="post-content">
              <%= comment.content %>
            </div>  
          </td>  
        </tr>
      <% end %>  
    </table>
    <h3>この投稿にコメントしましょう</h3>
    <%= form_for (@comment), url: post_comments_path(post_id: @post.id) do |f| %>
      <div class="form">
        <div class="form-body">
           <%= render partial: "partials/error_message", locals: { thing: @comment } %>
           <%= f.text_field :content, :class => "form-control" %>
           <%= f.submit "投稿", :class => "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <h1 class="form-heading">Do you want edit your profile?</h1>
    <div class="form users-form">
      <%= render partial: "partials/error_message", locals: { thing: @user } %>
      <%= form_for (@user) do |f| %>
        <div class="form-group">
          <%= f.label :nickname, "Nickname" %>
          <%= f.text_field :nickname, :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email, "Email" %>
          <%= f.email_field :email, :class => "form-control" %>
        </div>
        <div class="form-group">  
          <%= f.label :password, "Password" %>
          <%= f.password_field :password, :class => "form-control" %>
        </div>
        <div class="form-group">  
          <%= f.label :image, "Image" %>
          <%= f.file_field :image %>
        </div>
        <div class="form-group">  
          <%= f.submit "編集", :class => "btn btn-primary" %>
        </div>   
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="container">
    <h1 class="users-heading">User List</h1>
    <table class="table table-bordered" >
      <% @users.each do |user| %>
        <div class="users-index-item">    
          <tr><td>
            <%= image_tag user.image.thumb.url, class: "users-index-image"  %>
          </td><td>
            <%= link_to(user.nickname, user_path(user)) %>
          </td></tr>
        </div>
      <% end %>  
    </table>
  </div>
</div>  

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="menu-left">
      <h2><%= @user.nickname %></h2>
      <%= image_tag @user.image.thumb.url,class: "current-user-image" %>
      <% if @user.id == @current_user.id %>
        <p>email:<%= @user.email %></p>
        <%= link_to("Edit", edit_user_path(@user)) %><br>
      <% end %>    
    </div>
    <div class="menu-right">
      <% if @user.id == @current_user.id %>
        <h1>自分の投稿を振り返ってみましょう</h1>
      <% else %>  
        <h1>友達の投稿を覗いてみましょう</h1>
      <% end %>
      <% if @posts.empty? %>
        <div class="no-posts">
          まだ投稿がありません
        </div>
      <% else %>
        <table class="table table-bordered">
          <%= render :partial => "posts/post", :collection => @posts %>
        </table>
      <% end %>   
    </div>
  </div>
</div>